use crate::services::auth::permissions::*;

pub const ROLE_ADMIN: i32 = READ | WRITE | DELETE | UPDATE | EXECUTE | ADMIN | MANAGE_USERS | INVITE_USERS | VIEW_FINANCES | MANAGE_FINANCES;
pub const ROLE_USER: i32 = READ | WRITE | UPDATE | INVITE_USERS | VIEW_FINANCES;
